version: "3.9"

volumes:
  db-volume:

secrets:
  postgres_password:
    file: ./POSTGRES_PASSWORD

services:
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment: 
      - POSTGRES_USER=cardapio
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cardapio"]
      interval: 30s
      timeout: 30s
      retries: 3
    secrets:
      - postgres_password
    volumes:
      - db-volume:/var/lib/postgresql/data

  auth_service:
    build: ./auth_service
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://auth:auth@db:5432/auth?search_path=auth,auth_password
      - PASSWORD_DATABASE_URL=postgres://auth_password:auth_password@db:5432/auth?schema_path=auth_password
      - DATABASE_NAME=auth
      - SESSION_SECRET=bod&F069|)x|Rc)OYqau'_J.bP3k>zH9|QSVGRA~7ekiY;bW_KeA~]88%m1fktoNz
    volumes:
      - ./auth_service:/usr/src/app

  menu_service:
    build: ./menu_service
    ports:
      - '3001:3001'
    depends_on: 
      - db 
    environment:
      - RACK_ENV=development
      - DATABASE_URL=postgres://cardapio:cardapio@db:5432/cardapio
    volumes:
      - ./menu_service:/usr/src/app
